/*! Copyright (c) mharty.com */
jQuery(document).ready(function(n){var t=n(".mh_share"),e=n(".mh_share ul");function o(t){var e;return(t=t||window.event).which?e=3==t.which:t.button&&(e=2==t.button),e}function s(){var t="";return window.getSelection?t=window.getSelection().toString():document.selection&&"Control"!=document.selection.type&&(t=document.selection.createRange().text),t}n("body").on("click",".mh-loveit",function(){var e=n(this),t=n(this).attr("id");n(this);if(e.hasClass("loved"))return!1;if(n(this).hasClass("inactive"))return!1;t={action:"mh-loveit",loves_id:t,loveit_nonce:mhLoveit.loveitNonce};return n.post(mhLoveit.ajaxurl,t,function(t){e.find("span").html(t),e.addClass("loved").attr("title","أنت معجب بهذا!"),e.find("span").css({opacity:1,width:"auto"})}),n(this).addClass("inactive"),!1}),
//share pop-up
t.length&&(n("body").on("click",".post_share_item_url",function(){var t=n(this).prop("href"),e=n(window).width()/2-275,o=n(window).height()/2-225,o=window.open(t,"","scrollbars=1, height=450, width=550, left="+e+", top="+o);return window.focus&&o.focus(),!1}),//end share popup
//hover 
e.hasClass("mh_share_type_hover")&&e.hover(function(){n(this).addClass("hover"),n(".mhc_scroll_top").fadeOut(),n(".mh_quick_form").fadeOut()},function(){n(this).removeClass("hover"),n(".mhc_scroll_top").fadeIn(),n(".mh_quick_form").fadeIn()})),n("body").hasClass("mh_selecttweet")&&(
// select & tweet
n(".entry-content").mousedown(function(t){n("body").attr("mouse-top",t.clientY+window.pageYOffset),n("body").attr("mouse-left",t.clientX),!o(t)&&0<s().length&&(n(".mh-select-tweet").remove(),document.getSelection().removeAllRanges())}),n(".entry-content").mouseup(function(t){n(t.target);var e=s();5<e.length&&!o(t)&&(mts=n("body").attr("mouse-top"),mte=t.clientY+window.pageYOffset,mt=parseInt(mts)<parseInt(mte)?mts:mte,mlp=n("body").attr("mouse-left"),mrp=t.clientX,ml=parseInt(mlp)+(parseInt(mrp)-parseInt(mlp))/2,sl=window.location.href.split("?")[0],maxl=114,e=e.substring(0,maxl),
// append the sharing button
n("body").append('<a href="https://twitter.com/share?url='+encodeURIComponent(sl)+"&text="+encodeURIComponent(e)+"\" class='mh-select-tweet mh-select-tweet-icon mh-icon-before' onclick=\"window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;\"></a>"),n(".mh-select-tweet").css({position:"absolute",top:parseInt(mt)-55,left:parseInt(ml)}))}))});